openapi: 3.0.0
info:
  description: API for traces
  title: API
  version: 1.0.0
servers:
- url: /
paths:
  /groups:
    get:
      operationId: GetGroupList
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGroupListResponse'
          description: Groups info.
    post:
      operationId: CreateGroup
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateGroupResponse'
          description: Created group info.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error response.
  /traces:
    post:
      operationId: StartTrace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartTraceRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartTraceResponse'
          description: Started trace info.
  /traces/{uuid}:
    put:
      operationId: EndTrace
      parameters:
      - explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Trace ended successfully.
  /events:
    get:
      operationId: GetEventList
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEventListResponse'
          description: Event info.
    post:
      operationId: SendEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEventRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendEventResponse'
          description: Event info.
  /events/{uuid}:
    get:
      operationId: GetEvent
      parameters:
      - explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEventResponse'
          description: Event info.
    put:
      operationId: FixEvent
      parameters:
      - explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Event fixed successfully.
components:
  schemas:
    CreateGroupResponse:
      example:
        uuid: uuid
      properties:
        uuid:
          type: string
      required:
      - uuid
      type: object
    StartTraceRequest:
      example:
        component: component
        parent_uuid: parent_uuid
        group_uuid: group_uuid
        title: title
      properties:
        group_uuid:
          type: string
        parent_uuid:
          type: string
        title:
          type: string
        component:
          type: string
      required:
      - component
      - title
      type: object
    StartTraceResponse:
      example:
        component: component
        parent_uuid: parent_uuid
        start: start
        group_uuid: group_uuid
        end: end
        finished: true
        title: title
        uuid: uuid
      properties:
        uuid:
          type: string
        group_uuid:
          type: string
        parent_uuid:
          type: string
        start:
          type: string
        end:
          type: string
        title:
          type: string
        component:
          type: string
        finished:
          type: boolean
      required:
      - component
      - end
      - finished
      - start
      - title
      - uuid
      type: object
    SendEventRequest:
      example:
        component: component
        trace_uuid: trace_uuid
        payload:
          key: payload
        group_uuid: group_uuid
        message: message
        priority: priority
      properties:
        group_uuid:
          type: string
        trace_uuid:
          type: string
        message:
          type: string
        component:
          type: string
        priority:
          type: string
        payload:
          additionalProperties:
            type: string
          type: object
      required:
      - component
      - message
      - priority
      type: object
    Event:
      example:
        trace_uuid: trace_uuid
        payload:
          key: payload
        fixed: true
        time: time
        message: message
        priority: priority
        uuid: uuid
      properties:
        uuid:
          type: string
        trace_uuid:
          type: string
        message:
          type: string
        priority:
          type: string
        fixed:
          type: boolean
        time:
          type: string
        payload:
          additionalProperties:
            type: string
          type: object
      required:
      - fixed
      - message
      - payload
      - priority
      - time
      - trace_uuid
      - uuid
      type: object
    SendEventResponse:
      $ref: '#/components/schemas/Event'
    GetEventListResponse:
      example:
        items:
        - trace_uuid: trace_uuid
          payload:
            key: payload
          fixed: true
          time: time
          message: message
          priority: priority
          uuid: uuid
        - trace_uuid: trace_uuid
          payload:
            key: payload
          fixed: true
          time: time
          message: message
          priority: priority
          uuid: uuid
      properties:
        items:
          items:
            $ref: '#/components/schemas/Event'
          type: array
      required:
      - items
      type: object
    GetEventResponse:
      $ref: '#/components/schemas/Event'
    Trace:
      example:
        component: component
        parent_uuid: parent_uuid
        children:
        - null
        - null
        start: start
        group_uuid: group_uuid
        end: end
        finished: true
        title: title
        uuid: uuid
        events:
        - trace_uuid: trace_uuid
          payload:
            key: payload
          fixed: true
          time: time
          message: message
          priority: priority
          uuid: uuid
        - trace_uuid: trace_uuid
          payload:
            key: payload
          fixed: true
          time: time
          message: message
          priority: priority
          uuid: uuid
      properties:
        uuid:
          type: string
        group_uuid:
          type: string
        parent_uuid:
          type: string
        start:
          type: string
        end:
          type: string
        title:
          type: string
        component:
          type: string
        finished:
          type: boolean
        children:
          items:
            $ref: '#/components/schemas/Trace'
          type: array
        events:
          items:
            $ref: '#/components/schemas/Event'
          type: array
      required:
      - children
      - component
      - end
      - events
      - finished
      - group_uuid
      - start
      - title
      - uuid
      type: object
    Group:
      example:
        traces:
        - component: component
          parent_uuid: parent_uuid
          children:
          - null
          - null
          start: start
          group_uuid: group_uuid
          end: end
          finished: true
          title: title
          uuid: uuid
          events:
          - trace_uuid: trace_uuid
            payload:
              key: payload
            fixed: true
            time: time
            message: message
            priority: priority
            uuid: uuid
          - trace_uuid: trace_uuid
            payload:
              key: payload
            fixed: true
            time: time
            message: message
            priority: priority
            uuid: uuid
        - component: component
          parent_uuid: parent_uuid
          children:
          - null
          - null
          start: start
          group_uuid: group_uuid
          end: end
          finished: true
          title: title
          uuid: uuid
          events:
          - trace_uuid: trace_uuid
            payload:
              key: payload
            fixed: true
            time: time
            message: message
            priority: priority
            uuid: uuid
          - trace_uuid: trace_uuid
            payload:
              key: payload
            fixed: true
            time: time
            message: message
            priority: priority
            uuid: uuid
        uuid: uuid
      properties:
        uuid:
          type: string
        traces:
          items:
            $ref: '#/components/schemas/Trace'
          type: array
      required:
      - traces
      - uuid
      type: object
    GetGroupListResponse:
      example:
        active:
        - traces:
          - component: component
            parent_uuid: parent_uuid
            children:
            - null
            - null
            start: start
            group_uuid: group_uuid
            end: end
            finished: true
            title: title
            uuid: uuid
            events:
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
          - component: component
            parent_uuid: parent_uuid
            children:
            - null
            - null
            start: start
            group_uuid: group_uuid
            end: end
            finished: true
            title: title
            uuid: uuid
            events:
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
          uuid: uuid
        - traces:
          - component: component
            parent_uuid: parent_uuid
            children:
            - null
            - null
            start: start
            group_uuid: group_uuid
            end: end
            finished: true
            title: title
            uuid: uuid
            events:
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
          - component: component
            parent_uuid: parent_uuid
            children:
            - null
            - null
            start: start
            group_uuid: group_uuid
            end: end
            finished: true
            title: title
            uuid: uuid
            events:
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
          uuid: uuid
        fixed:
        - traces:
          - component: component
            parent_uuid: parent_uuid
            children:
            - null
            - null
            start: start
            group_uuid: group_uuid
            end: end
            finished: true
            title: title
            uuid: uuid
            events:
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
          - component: component
            parent_uuid: parent_uuid
            children:
            - null
            - null
            start: start
            group_uuid: group_uuid
            end: end
            finished: true
            title: title
            uuid: uuid
            events:
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
          uuid: uuid
        - traces:
          - component: component
            parent_uuid: parent_uuid
            children:
            - null
            - null
            start: start
            group_uuid: group_uuid
            end: end
            finished: true
            title: title
            uuid: uuid
            events:
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
          - component: component
            parent_uuid: parent_uuid
            children:
            - null
            - null
            start: start
            group_uuid: group_uuid
            end: end
            finished: true
            title: title
            uuid: uuid
            events:
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
            - trace_uuid: trace_uuid
              payload:
                key: payload
              fixed: true
              time: time
              message: message
              priority: priority
              uuid: uuid
          uuid: uuid
      properties:
        active:
          items:
            $ref: '#/components/schemas/Group'
          type: array
        fixed:
          items:
            $ref: '#/components/schemas/Group'
          type: array
      required:
      - active
      - fixed
      type: object
    Error:
      properties:
        error:
          type: string
        comment:
          type: string
      required:
      - comment
      - error
      type: object
